//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsPropertyTypeGroup
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cmsPropertyTypeGroup()
        {
            this.cmsPropertyTypes = new HashSet<cmsPropertyType>();
        }
    
        public int id { get; set; }
        public int contenttypeNodeId { get; set; }
        public string text { get; set; }
        public int sortorder { get; set; }
        public System.Guid uniqueID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsPropertyType> cmsPropertyTypes { get; set; }
    }
}
