//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class cmsPropertyType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cmsPropertyType()
        {
            this.cmsPropertyDatas = new HashSet<cmsPropertyData>();
            this.cmsTagRelationships = new HashSet<cmsTagRelationship>();
        }
    
        public int id { get; set; }
        public int dataTypeId { get; set; }
        public int contentTypeId { get; set; }
        public Nullable<int> propertyTypeGroupId { get; set; }
        public string Alias { get; set; }
        public string Name { get; set; }
        public int sortOrder { get; set; }
        public bool mandatory { get; set; }
        public string validationRegExp { get; set; }
        public string Description { get; set; }
        public System.Guid UniqueID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsPropertyData> cmsPropertyDatas { get; set; }
        public virtual cmsPropertyTypeGroup cmsPropertyTypeGroup { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTagRelationship> cmsTagRelationships { get; set; }
    }
}
