//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Contact
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Contact()
        {
            this.ContactNotes = new HashSet<ContactNote>();
            this.MailingListMembers = new HashSet<MailingListMember>();
        }
    
        public int ID { get; set; }
        public Nullable<int> HouseholdID { get; set; }
        public Nullable<int> AccountID { get; set; }
        public string ImportedID { get; set; }
        public string HouseholdImportedID { get; set; }
        public string AccountImportedID { get; set; }
        public string LastName { get; set; }
        public string FirstName { get; set; }
        public string Salutation { get; set; }
        public string Name { get; set; }
        public string MailingStreet { get; set; }
        public string MailingCity { get; set; }
        public string MailingState { get; set; }
        public string MailingPostalCode { get; set; }
        public string Phone { get; set; }
        public string MobilePhone { get; set; }
        public string HomePhone { get; set; }
        public string Email { get; set; }
        public string OwnerID { get; set; }
        public string HomeEmail { get; set; }
        public string WorkEmail { get; set; }
        public string WorkPhone { get; set; }
        public int HouseholdFamilyRoleID { get; set; }
    
        public virtual Account Account { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactNote> ContactNotes { get; set; }
        public virtual HouseholdFamilyRole HouseholdFamilyRole { get; set; }
        public virtual Household Household { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MailingListMember> MailingListMembers { get; set; }
    }
}
