//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoNode
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoNode()
        {
            this.cmsContents = new HashSet<cmsContent>();
            this.cmsContentTypes = new HashSet<cmsContentType>();
            this.cmsDataTypes = new HashSet<cmsDataType>();
            this.cmsDocuments = new HashSet<cmsDocument>();
            this.cmsDocumentTypes = new HashSet<cmsDocumentType>();
            this.cmsMemberTypes = new HashSet<cmsMemberType>();
            this.cmsPropertyDatas = new HashSet<cmsPropertyData>();
            this.cmsTasks = new HashSet<cmsTask>();
            this.cmsTemplates = new HashSet<cmsTemplate>();
            this.umbracoAccesses = new HashSet<umbracoAccess>();
            this.umbracoAccesses1 = new HashSet<umbracoAccess>();
            this.umbracoAccesses2 = new HashSet<umbracoAccess>();
            this.umbracoDomains = new HashSet<umbracoDomain>();
            this.umbracoNode1 = new HashSet<umbracoNode>();
            this.umbracoRelations = new HashSet<umbracoRelation>();
            this.umbracoRelations1 = new HashSet<umbracoRelation>();
            this.umbracoUser2NodeNotify = new HashSet<umbracoUser2NodeNotify>();
            this.umbracoUser2NodePermission = new HashSet<umbracoUser2NodePermission>();
            this.umbracoNode11 = new HashSet<umbracoNode>();
            this.umbracoNodes = new HashSet<umbracoNode>();
            this.cmsMembers = new HashSet<cmsMember>();
        }
    
        public int id { get; set; }
        public bool trashed { get; set; }
        public int parentID { get; set; }
        public Nullable<int> nodeUser { get; set; }
        public int level { get; set; }
        public string path { get; set; }
        public int sortOrder { get; set; }
        public System.Guid uniqueID { get; set; }
        public string text { get; set; }
        public Nullable<System.Guid> nodeObjectType { get; set; }
        public System.DateTime createDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsContent> cmsContents { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsContentType> cmsContentTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsDataType> cmsDataTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsDocument> cmsDocuments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsDocumentType> cmsDocumentTypes { get; set; }
        public virtual cmsMember cmsMember { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsMemberType> cmsMemberTypes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsPropertyData> cmsPropertyDatas { get; set; }
        public virtual cmsStylesheet cmsStylesheet { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTask> cmsTasks { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsTemplate> cmsTemplates { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccess> umbracoAccesses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccess> umbracoAccesses1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccess> umbracoAccesses2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoDomain> umbracoDomains { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoNode> umbracoNode1 { get; set; }
        public virtual umbracoNode umbracoNode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoRelation> umbracoRelations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoRelation> umbracoRelations1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUser2NodeNotify> umbracoUser2NodeNotify { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoUser2NodePermission> umbracoUser2NodePermission { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoNode> umbracoNode11 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoNode> umbracoNodes { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cmsMember> cmsMembers { get; set; }
    }
}
