//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoAccess
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public umbracoAccess()
        {
            this.umbracoAccessRules = new HashSet<umbracoAccessRule>();
        }
    
        public System.Guid id { get; set; }
        public int nodeId { get; set; }
        public int loginNodeId { get; set; }
        public int noAccessNodeId { get; set; }
        public System.DateTime createDate { get; set; }
        public System.DateTime updateDate { get; set; }
    
        public virtual umbracoNode umbracoNode { get; set; }
        public virtual umbracoNode umbracoNode1 { get; set; }
        public virtual umbracoNode umbracoNode2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<umbracoAccessRule> umbracoAccessRules { get; set; }
    }
}
