//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoCacheInstruction
    {
        public int id { get; set; }
        public System.DateTime utcStamp { get; set; }
        public string jsonInstruction { get; set; }
        public string originated { get; set; }
    }
}
