//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class umbracoExternalLogin
    {
        public int id { get; set; }
        public int userId { get; set; }
        public string loginProvider { get; set; }
        public string providerKey { get; set; }
        public System.DateTime createDate { get; set; }
    }
}
