//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WillingToJoin.Util.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class WTJContext : DbContext
    {
        public WTJContext()
            : base("name=WTJContext")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccountNote> AccountNotes { get; set; }
        public virtual DbSet<Account> Accounts { get; set; }
        public virtual DbSet<AccountStatu> AccountStatus { get; set; }
        public virtual DbSet<AspNetRole> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaim> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogin> AspNetUserLogins { get; set; }
        public virtual DbSet<cmsContent> cmsContents { get; set; }
        public virtual DbSet<cmsContentType> cmsContentTypes { get; set; }
        public virtual DbSet<cmsContentTypeAllowedContentType> cmsContentTypeAllowedContentTypes { get; set; }
        public virtual DbSet<cmsContentVersion> cmsContentVersions { get; set; }
        public virtual DbSet<cmsContentXml> cmsContentXmls { get; set; }
        public virtual DbSet<cmsDataType> cmsDataTypes { get; set; }
        public virtual DbSet<cmsDataTypePreValue> cmsDataTypePreValues { get; set; }
        public virtual DbSet<cmsDictionary> cmsDictionaries { get; set; }
        public virtual DbSet<cmsDocument> cmsDocuments { get; set; }
        public virtual DbSet<cmsDocumentType> cmsDocumentTypes { get; set; }
        public virtual DbSet<cmsLanguageText> cmsLanguageTexts { get; set; }
        public virtual DbSet<cmsMacro> cmsMacroes { get; set; }
        public virtual DbSet<cmsMacroProperty> cmsMacroProperties { get; set; }
        public virtual DbSet<cmsMember> cmsMembers { get; set; }
        public virtual DbSet<cmsMemberType> cmsMemberTypes { get; set; }
        public virtual DbSet<cmsPreviewXml> cmsPreviewXmls { get; set; }
        public virtual DbSet<cmsPropertyData> cmsPropertyDatas { get; set; }
        public virtual DbSet<cmsPropertyType> cmsPropertyTypes { get; set; }
        public virtual DbSet<cmsPropertyTypeGroup> cmsPropertyTypeGroups { get; set; }
        public virtual DbSet<cmsStylesheet> cmsStylesheets { get; set; }
        public virtual DbSet<cmsStylesheetProperty> cmsStylesheetProperties { get; set; }
        public virtual DbSet<cmsTagRelationship> cmsTagRelationships { get; set; }
        public virtual DbSet<cmsTag> cmsTags { get; set; }
        public virtual DbSet<cmsTask> cmsTasks { get; set; }
        public virtual DbSet<cmsTaskType> cmsTaskTypes { get; set; }
        public virtual DbSet<cmsTemplate> cmsTemplates { get; set; }
        public virtual DbSet<ContactNote> ContactNotes { get; set; }
        public virtual DbSet<Contact> Contacts { get; set; }
        public virtual DbSet<HouseholdFamilyRole> HouseholdFamilyRoles { get; set; }
        public virtual DbSet<HouseholdNote> HouseholdNotes { get; set; }
        public virtual DbSet<Household> Households { get; set; }
        public virtual DbSet<HouseholdStatu> HouseholdStatus { get; set; }
        public virtual DbSet<MailingListMember> MailingListMembers { get; set; }
        public virtual DbSet<MailingList> MailingLists { get; set; }
        public virtual DbSet<MailingListType> MailingListTypes { get; set; }
        public virtual DbSet<NoteType> NoteTypes { get; set; }
        public virtual DbSet<umbracoAccess> umbracoAccesses { get; set; }
        public virtual DbSet<umbracoAccessRule> umbracoAccessRules { get; set; }
        public virtual DbSet<umbracoCacheInstruction> umbracoCacheInstructions { get; set; }
        public virtual DbSet<umbracoDeployChecksum> umbracoDeployChecksums { get; set; }
        public virtual DbSet<umbracoDeployDependency> umbracoDeployDependencies { get; set; }
        public virtual DbSet<umbracoDomain> umbracoDomains { get; set; }
        public virtual DbSet<umbracoExternalLogin> umbracoExternalLogins { get; set; }
        public virtual DbSet<umbracoLanguage> umbracoLanguages { get; set; }
        public virtual DbSet<umbracoLog> umbracoLogs { get; set; }
        public virtual DbSet<umbracoMigration> umbracoMigrations { get; set; }
        public virtual DbSet<umbracoNode> umbracoNodes { get; set; }
        public virtual DbSet<umbracoRelation> umbracoRelations { get; set; }
        public virtual DbSet<umbracoRelationType> umbracoRelationTypes { get; set; }
        public virtual DbSet<umbracoServer> umbracoServers { get; set; }
        public virtual DbSet<umbracoUser> umbracoUsers { get; set; }
        public virtual DbSet<umbracoUser2app> umbracoUser2app { get; set; }
        public virtual DbSet<umbracoUser2NodeNotify> umbracoUser2NodeNotify { get; set; }
        public virtual DbSet<umbracoUser2NodePermission> umbracoUser2NodePermission { get; set; }
        public virtual DbSet<umbracoUserType> umbracoUserTypes { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
    }
}
