
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WillingToJoin.Shared.Data
{

using System;
    using System.Collections.Generic;
    
public partial class Transaction
{

    public int ID { get; set; }

    public Nullable<int> HouseholdID { get; set; }

    public Nullable<int> TransTypeID { get; set; }

    public Nullable<int> TransIncrID { get; set; }

    public Nullable<int> TransMethID { get; set; }

    public System.DateTime Date { get; set; }

    public decimal Amount { get; set; }



    public virtual Household Household { get; set; }

    public virtual TransactionType TransactionType { get; set; }

    public virtual TransactionIncrement TransactionIncrement { get; set; }

    public virtual TransactionMethod TransactionMethod { get; set; }

}

}
