

//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace WillingToJoin.Shared.Data
{

using System;
using System.Data.Entity;
using System.Data.Entity.Infrastructure;


public partial class WTJContext : DbContext
{
    public WTJContext()
        : base("name=WTJContext")
    {

    }

    protected override void OnModelCreating(DbModelBuilder modelBuilder)
    {
        throw new UnintentionalCodeFirstException();
    }


    public virtual DbSet<AccountNote> AccountNotes { get; set; }

    public virtual DbSet<Account> Accounts { get; set; }

    public virtual DbSet<AccountStatus> AccountStatuses { get; set; }

    public virtual DbSet<ContactNote> ContactNotes { get; set; }

    public virtual DbSet<Contact> Contacts { get; set; }

    public virtual DbSet<ContactStatus> ContactStatuses { get; set; }

    public virtual DbSet<HouseholdFamilyRole> HouseholdFamilyRoles { get; set; }

    public virtual DbSet<HouseholdNote> HouseholdNotes { get; set; }

    public virtual DbSet<Household> Households { get; set; }

    public virtual DbSet<HouseholdStatus> HouseholdStatuses { get; set; }

    public virtual DbSet<MailingListMember> MailingListMembers { get; set; }

    public virtual DbSet<MailingList> MailingLists { get; set; }

    public virtual DbSet<MailingListType> MailingListTypes { get; set; }

    public virtual DbSet<NoteType> NoteTypes { get; set; }

    public virtual DbSet<Transaction> Transactions { get; set; }

    public virtual DbSet<TransactionIncrement> TransactionIncrements { get; set; }

    public virtual DbSet<TransactionMethod> TransactionMethods { get; set; }

    public virtual DbSet<TransactionType> TransactionTypes { get; set; }

}

}

